namespace trading_platform.Model.KoreaInvestment;

public static class TransactionIdTable {
  public static string GetRelativeUri(string transId) => transId switch {
    "CTCA0903R" => "/uapi/domestic-stock/v1/quotations/chk-holiday", // 국내 휴장일 조회
    "CTFO6118R" => "/uapi/domestic-futureoption/v1/trading/inquire-balance", // 선물옵션 잔고현황
    "CTFO6159R" => "/uapi/domestic-futureoption/v1/trading/inquire-balance-valuation-pl", // 선물옵션 잔고평가손익내역
    "CTPF1002R" => "/uapi/domestic-stock/v1/quotations/search-stock-info", // 주식기본조회
    "CTPF1604R" => "/uapi/domestic-stock/v1/quotations/search-info", // 상품기본조회
    "CTRP6550R" => "/uapi/domestic-futureoption/v1/trading/inquire-deposit", // 선물옵션 총자산현황
    "CTSC0008U" => "/uapi/domestic-stock/v1/trading/order-resv", // 주식예약주문
    "FHKST01010100" => "/uapi/domestic-stock/v1/quotations/inquire-price", // 국내주식 현재가 시세
    "FHKST01010200" => "/uapi/domestic-stock/v1/quotations/inquire-asking-price-exp-ccn", // 국내주식 호가
    "FHKST03010100" => "/uapi/domestic-stock/v1/quotations/inquire-daily-itemchartprice", // 국내주식 기간별 시세(일/주/월/년)
    "FHKST03030100" => "/uapi/overseas-price/v1/quotations/inquire-daily-chartprice", // 해외주식 종목/지수/환율기간별시세(일/주/월/년)
    "FHKST121600C0" => "/uapi/etfetn/v1/quotations/inquire-component-stock-price", // ETF 구성종목시세
    "FHKST66430100" => "/uapi/domestic-stock/v1/finance/balance-sheet", // 국내주식 대차대조표
    "FHKST66430300" => "/uapi/domestic-stock/v1/finance/financial-ratio", // 국내주식 재무비율
    "FHMIF10000000" => "/uapi/domestic-futureoption/v1/quotations/inquire-price", // 선물옵션 시세
    "FHMIF10010000" => "/uapi/domestic-futureoption/v1/quotations/inquire-asking-price", // 선물옵션 시세호가
    "FHPST02440000" => "/uapi/etfetn/v1/quotations/nav-comparison-trend", // NAV 비교추이(종목)
    "FHPST07020000" => "/uapi/domestic-stock/v1/quotations/comp-interest", // 금리 종합(국내채권/금리)
    "FHPTJ04040000" => "/uapi/domestic-stock/v1/quotations/inquire-investor-daily-by-market", // 시장별 투자자매매동향(일별)
    "FHPUP02100000" => "/uapi/domestic-stock/v1/quotations/inquire-index-price", // 국내 업종 현재 지수
    "FHPUP02120000" => "/uapi/domestic-stock/v1/quotations/inquire-index-daily-price", // 국내업종 일자별지수
    "HHDFC55010000" => "/uapi/overseas-futureoption/v1/quotations/inquire-price", // 해외선물종목현재가
    "HHDFC55010100" => "/uapi/overseas-futureoption/v1/quotations/stock-detail", // 해외선물종목상세
    "HHDFC55200000" => "/uapi/overseas-futureoption/v1/quotations/search-contract-detail", // 해외선물 상품기본정보
    "HHDFC86000000" => "/uapi/overseas-futureoption/v1/quotations/inquire-asking-price", // 해외선물 호가
    "HHDFS76200200" => "/uapi/overseas-price/v1/quotations/price-detail", // 해외주식 현재가상세
    "HHDFS76240000" => "/uapi/overseas-price/v1/quotations/dailyprice", // 해외주식 기간별시세
    "HHMCM000002C0" => "/uapi/domestic-stock/v1/quotations/market-time", // 국내선물 영업일조회
    "TTTC0011U" or "TTTC0012U" or "VTTTC0011U" or "VTTTC0012U" => "/uapi/domestic-stock/v1/trading/order-cash", // 국내주식 현금 매도/매수
    "TTTC0013U" => "/uapi/domestic-stock/v1/trading/order-rvsecncl", // 주식주문(정정취소)
    "TTTC0084R" => "/uapi/domestic-stock/v1/trading/inquire-psbl-rvsecncl", // 주식정정취소가능주문조회
    "TTTC8408R" => "/uapi/domestic-stock/v1/trading/inquire-psbl-sell", // 매도가능수량조회
    "TTTC8434R" => "/uapi/domestic-stock/v1/trading/inquire-balance", // 국내주식 잔고 조회
    "TTTO1101U" or "STTN1101U" => "/uapi/domestic-futureoption/v1/trading/order", // 선물옵션 주문
    "TTTO1103U" or "STTN1103U" => "/uapi/domestic-futureoption/v1/trading/order-rvsecncl", // 선물옵션 정정취소주문
    "TTTS3007R" => "/uapi/overseas-stock/v1/trading/inquire-psamount", // 해외주식 매수가능금액조회
    "TTTS3012R" => "/uapi/overseas-stock/v1/trading/inquire-balance", // 해외주식 잔고
    "TTTS3039R" => "/uapi/overseas-stock/v1/trading/inquire-period-profit", // 해외주식 기간손익
    "TTTT1002U" or "TTTT1006U" => "/uapi/overseas-stock/v1/trading/order", // 해외주식 주문
    "TTTT1004U" => "/uapi/overseas-stock/v1/trading/order-rvsecncl", // 해외주식 정정취소주문
    "TTTT3014U" or "TTTT3016U" or "TTTS3013U" => "/uapi/overseas-stock/v1/trading/order-resv", // 해외주식 예약주문접수
    "TTTT3039R" or "TTTS3014R" => "/uapi/overseas-stock/v1/trading/order-resv-list", // 해외주식 예약주문조회
    _ => throw new NotImplementedException("지원되지 않는 TR ID입니다.")
  };
  public static HttpMethod GetHttpMethod(string transId) => transId switch {
    "CTCA0903R" => HttpMethod.Get, // 국내 휴장일 조회
    "CTFO6118R" => HttpMethod.Get, // 선물옵션 잔고현황
    "CTFO6159R" => HttpMethod.Get, // 선물옵션 잔고평가손익내역
    "CTPF1002R" => HttpMethod.Get, // 주식기본조회
    "CTPF1604R" => HttpMethod.Get, // 상품기본조회
    "CTRP6550R" => HttpMethod.Get, // 선물옵션 총자산현황
    "CTSC0008U" => HttpMethod.Post, // 주식예약주문
    "FHKST01010100" => HttpMethod.Get, // 국내주식 현재가 시세
    "FHKST01010200" => HttpMethod.Get,
    "FHKST03010100" => HttpMethod.Get, // 국내주식 기간별 시세(일/주/월/년)
    "FHKST03030100" => HttpMethod.Get, // 해외주식 종목/지수/환율기간별시세(일/주/월/년)
    "FHKST121600C0" => HttpMethod.Get, // ETF 구성종목시세
    "FHKST66430100" => HttpMethod.Get, // 국내주식 대차대조표
    "FHKST66430300" => HttpMethod.Get, // 국내주식 재무비율
    "FHMIF10000000" => HttpMethod.Get, // 선물옵션 시세
    "FHMIF10010000" => HttpMethod.Get, // 선물옵션 시세호가
    "FHPST02440000" => HttpMethod.Get, // NAV 비교추이(종목)
    "FHPST07020000" => HttpMethod.Get, // 금리 종합(국내채권/금리)
    "FHPTJ04040000" => HttpMethod.Get, // 시장별 투자자매매동향(일별)
    "FHPUP02100000" => HttpMethod.Get, // 국내 업종 현재 지수
    "FHPUP02120000" => HttpMethod.Get, // 국내업종 일자별지수
    "HHDFC55010000" => HttpMethod.Get, // 해외선물종목현재가
    "HHDFC55010100" => HttpMethod.Get, // 해외선물종목상세
    "HHDFC55200000" => HttpMethod.Get, // 해외선물 상품기본정보
    "HHDFC86000000" => HttpMethod.Get, // 해외선물 호가
    "HHDFS76200200" => HttpMethod.Get, // 해외주식 현재가상세
    "HHDFS76240000" => HttpMethod.Get, // 해외주식 기간별시세
    "HHMCM000002C0" => HttpMethod.Get, // 국내선물 영업일조회
    "TTTC0011U" or "TTTC0012U" or "VTTTC0011U" or "VTTTC0012U" => HttpMethod.Post, // 국내주식 현금 매도/매수
    "TTTC0013U" => HttpMethod.Post, // 주식주문(정정취소)
    "TTTC0084R" => HttpMethod.Get, // 주식정정취소가능주문조회
    "TTTC8408R" => HttpMethod.Get, // 매도가능수량조회
    "TTTC8434R" => HttpMethod.Get, // 국내주식 잔고 조회
    "TTTO1101U" => HttpMethod.Post, // 선물옵션 주문
    "TTTO1103U" => HttpMethod.Post, // 선물옵션 정정취소주문
    "TTTS3007R" => HttpMethod.Get, // 해외주식 매수가능금액조회
    "TTTS3012R" => HttpMethod.Get, // 해외주식 잔고
    "TTTS3039R" => HttpMethod.Get, // 해외주식 기간손익
    "TTTT1002U" => HttpMethod.Post, // 해외주식 주문
    "TTTT1004U" => HttpMethod.Post, // 해외주식 정정취소주문
    "TTTT3014U" => HttpMethod.Post, // 해외주식 예약주문접수
    "TTTT3039R" => HttpMethod.Get, // 해외주식 예약주문조회
    _ => throw new NotImplementedException("지원되지 않는 TR ID입니다.")
  };
}